services:
  - type: web
    name: estevao-api
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec rails db:migrate && bundle exec rails s -p 3000 -b 0.0.0.0
    envVars:
      - key: RAILS_ENV
        value: production
